apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-deployment
  labels:
    app: mon-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mon-application
  template:
    metadata:
      labels:
        app: mon-application
    spec:
      containers:
      - name: mon-conteneur
        image: harbor-server.test.intel/agriculture/app2:latest # Remplacez par votre image Docker
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mon-service
  labels:
    app: mon-application
spec:
  selector:
    app: mon-application
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80          # Port exposé hors Kubernetes
    targetPort: 8080  # Port utilisé par l'application
